# Site Info
title: Adam Rumbold
tagline: 'Just a little bit further'
description: 'A personal blog covering tech, photograpy, running, travel and homebrew'
baseurl: ""
url: http://adamrumbold.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
future: true

version: 1.0.0

github:
  repo:           https://github.com/adamrumbold/adamrumbold.github.io

# About/contact
author:
  name: Adam Rumbold
  description: Adventures in <strong>mountain running, photography, coding, beer and fun!</strong>
  gravatar: 1a66e6580107fe3106bd4d33afca7ae1 # md5 hash of your email address
  photo: https://www.gravatar.com/avatar/1a66e6580107fe3106bd4d33afca7ae1?s=200
  contact:
    instagram: https://www.instagram.com/arumbold/
    github:    https://github.com/adamrumbold
    flickr:    https://www.flickr.com/photos/adamrumbold
    twitter:   https://twitter.com/arumbold
    email:     http://www.google.com/recaptcha/mailhide/d?k=01iSzk1Hp90UGxBxbMGDx_JA==&c=i5EDOxL4umdO1JfQb80ZzYl4b_k1Bw16ml3in2-EV50=
# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - {  Categories: '/blog/category/' }
    - {  Tags: '/blog/tag/' }
  About:          
    - '/about/'
  Github Project: 
    - 'http://adamrumbold.Githubub.io/'
  API:
    - 'http://api.adamrumbold.com/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/category/'

hero:
  image: /public/img/home_med.jpg
  caption: Storms rolling into the bush capital.

# Puglins
mathjax: true # whether support mathjax
google_analytics_token:  'UA-15638765-1'
disqus_short_name:  # leave blank if you don't want disqus



